@host=http://localhost:5023
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJBbWljaGFpIiwiZmFtaWx5X25hbWUiOiJNYWludGluYmFuZCIsImp0aSI6IjlhN2VjNDhkLTZkNzUtNDVmMC1iNWI1LWJjMzNkMTQyNzY4NiIsImV4cCI6MTcyNjA2NTQ3MCwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.ERRwfJVBO2F8OX3buKWdZsErmAPA2gHI4GxHPmLuwNE
POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}