@host=http://localhost:5023
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJBbWljaGFpIiwiZmFtaWx5X25hbWUiOiJNYWludGluYmFuZCIsImp0aSI6ImQ0YzE2OGU0LTM2ODQtNDk1Yy1iMDcyLTE4N2Y5MjNlYmMwMyIsImV4cCI6MTcyNjA1NTc1MywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.-eaFMnALDNx2K4wHYVGYuzyUEoV_Ui9_omGbKUUOJ9w

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}