@host = http://localhost:5023

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNWQwNTEzOS0wNjIzLTRjNWQtYjJlYi0xY2FhM2FkZjFkYmUiLCJnaXZlbl9uYW1lIjoiQW1pY2hhaSIsImZhbWlseV9uYW1lIjoiTWFpbnRpbmJhbmQiLCJqdGkiOiIxNmViYmQ3YS1iZWZhLTRhYjUtODBlMS03ODU3Y2FmMzRjNjgiLCJleHAiOjE3MjQwNzAzODgsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.g1exdU3qI0o32-x7QEv4aSaeRKw4_0RdOaK_eysKBrQ