@host = http://localhost:5023

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJBbWljaGFpIiwiZmFtaWx5X25hbWUiOiJNYWludGluYmFuZCIsImp0aSI6ImQ4OGVmYTM1LTZlZTctNDI2YS1hMzM5LWU4NzViNDc1OGRkNyIsImV4cCI6MTcyNTk3MzEyNywiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lciJ9.KL93Wjq9dUVQhNn8H_rMMHPcOjoGTmimyJqcXT5uBHc